# Generated by Django 2.2.10 on 2020-03-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200304_2313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagex",
            name="body",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
