# Generated by Django 2.2.10 on 2020-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200305_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagex',
            name='body',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
